version: '0.1.{build}'
configuration:
    - release
    - debug
os: Visual Studio 2015
before_build:
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 14 2015"
build:
    project: C:\projects\IndexedBuffer\build\IndexedBuffer.sln
    verbosity: detailed
test_script:
    - cd C:\projects\IndexedBuffer\build
    - ctest -VV -C %Configuration%
